version: '3'

services:
  redis_cache: 
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379" 
  
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD="${DATABASE_PASSWORD}"
      POSTGRES_NAME="${DATABASE_NAME}"
    container_name: routes_db
    volumes:
      - ./postgres:/var/lib/postgresql/data