
version: '3'

services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: router_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
